### ISSUE TITLE
`toHaveProp()` modifies parameter value

### ISSUE THREAD

**Issue by juffel** [blainekasten/enzyme-matchers#101]
Strangely the [`toHaveProp`](https://github.com/blainekasten/enzyme-matchers#tohaveproppropkeystring-propvalueany) matcher seems to modify the passed array value: 

```
it('check props', () => {
    const numberArray = [1, 2, 3];
    console.log(numberArray);                           // [ 1, 2, 3 ]
    expect(wrapper).toHaveProp('records', numberArray);
    console.log(numberArray);                           // [ 1 ]
});
```

I'm (apart from that happily 👍 ) using jasmine-enzyme 3.2.0 (and enzyme 2.8.2).

**Comment by juffel** [comment]
I dug a bit into this, and there seems to be an issue with the [`stringify`](https://github.com/blainekasten/enzyme-matchers/blob/master/packages/enzyme-matchers/src/utils/stringify.js) function when arrays are passed.

**Comment by blainekasten** [comment]
ahh yikes. That's not good. Could you submit a PR to fix it?

**Comment by moredip** [comment]
I ran into the same issue. It looks like it's due to [this line](https://github.com/blainekasten/enzyme-matchers/blob/2f6441c33044830c8798d6e2d6c9a8f6e7063b84/packages/enzyme-matchers/src/utils/stringify.js#L10) where the array value being stringified is mutated via a `.pop`.

I'd love to submit a PR to fix this but I'm not sure I understand what's going on with that pop operation. Can you explain? Or alternatively I could just submit a PR to remove the pop operation 😁.

**Comment by blainekasten** [comment]
@moredip I frankly don't remember what I was doing there.... haha

I would say, you could probably easily TDD this. Write a test that passes in an array and ensures the array does not change.

Then, as long as none of the other tests fail I'd say we did it right

**Comment by moredip** [comment]
Sounds good. Will work on getting a PR to you.
