### ISSUE TITLE
toHaveStyle checks the DOM before rendering

### ISSUE THREAD

**Issue by kiranps** [blainekasten/enzyme-matchers#63]
```js
function Fixture() {
  const style1 = { backgroundColor: 'red' };

  return (
    <div>
      <span id="style1" style={style1} />
    </div>
  );
}

const wrapper = mount(<Fixture />); 
```

```js
expect(wrapper.find('#style1')).toHaveStyle('backgroundColor', 'red');  // passes
```

```js
expect(wrapper.find('#style1')).toHaveStyle('background-color', 'red');  // fails
```

second case should pass and first should fail right

**Comment by blainekasten** [comment]
@kiranps nope, that's actually how it should be. With Enzyme, and specifically React, it's better to be testing against the props, rather than the DOM output. Testing the DOM output would technically be testing React to make sure they properly pass props to the DOM. That is not our job. We just want to test that components get the right props and render the expected vDOM description.

So in this case, you are expecting the span to have a prop style with `backgroundColor`!

**Comment by blainekasten** [comment]
I'm going to close the issue for now. Feel free to keep the conversation going, but I don't think there is anything actionable for me here at the moment.
