### ISSUE TITLE
Errors with flowtypes

### ISSUE THREAD

**Issue by SBoudrias** [blainekasten/enzyme-matchers#77]
Hey, adding this module to jest causes a lot of flow type checking errors:

```
node_modules/enzyme-matchers/src/assertions/toHaveText.js:10
 10: import type { EnzymeObject } from '../../../../types/EnzymeObject';
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ../../../../types/EnzymeObject. Required module not found
```

There might be a way to ignore these with a flowconfig, but it'd be better if it worked out of the box.

I wonder if maybe this could be fixed by `.npmignore` tje `src` directory as it is not used (`lib` folder is the actual module as far as I can tell)

**Comment by blainekasten** [comment]
I'd be happy to accept a PR to fix and clean up flow usage!

**Comment by blainekasten** [comment]
3.2.0 is out and _might_ fix this! 
Please give it a try and let me know if it fixes or not

https://github.com/blainekasten/enzyme-matchers/releases/tag/v3.2.0

**Comment by jfroom** [comment]
I've updated to 3.2.0, and am still encountering a similar problem. 
```
node_modules/enzyme-matchers/src/assertions/toBeChecked.js:9
  9: import type { EnzymeObject } from '../../../../types/EnzymeObject';
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ../../../../types/EnzymeObject. Required module not found
```

I think the issue is because there is a root repository for dev https://github.com/blainekasten/enzyme-matchers, the `types` exist off the root https://github.com/blainekasten/enzyme-matchers/types, and then each sub-package for `enzyme-matchers`, `jasmine-enzyme`, and `jest-enzyme` in https://github.com/blainekasten/enzyme-matchers/tree/master/packages get npm/yarn installed into a client project without the root project or types. The sub-packages then attempt to reference the non-existent types folder. 

Thoughts?

**Comment by jfroom** [comment]
FYI for anyone looking to just ignore the related errors in their project (until the wonderful team here can sort things out):

Add something like this to your [`.flowconfig` ignore section](https://flow.org/en/docs/config/ignore/):
```
[ignore]
.*/node_modules/enzyme-matchers/.*
.*/node_modules/jest-enzyme/.*
```

**Comment by blainekasten** [comment]
@jfroom thanks for all of this info. I'm on vacaition until the 19th. I'll make sure to look into these solutions then!

**Comment by blainekasten** [comment]
@jfroom @SBoudrias Can you try out 3.3.0?

**Comment by jfroom** [comment]
Looks like it's working! 

In my project, I've updated to 3.3.0 for `enzyme-matchers` and `jest-enzyme`, removed the `.flowconfig` ignores noted previously, and now the `flow` command no longer throws any warnings/errors on these packages. 

FWIW - I had to upgrade my create-react-app's `react-scripts` package to get `jest` to bump a few versions - probably because of the version required by `jest-enzyme`.
